name: 'Deploy to AWS S3 Docker'
description: 'Deploy a static website via AWS S3 Docker.'
inputs:
  bucket:
    description: 'The S3 bucket name Docker.'
    required: true
  bucket-region: 
    description: 'The region of the S3 bucket Docker.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files docker.'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website.'
runs:
  using: 'docker'
  image: 'Dockerfile'